#!/usr/bin/env node
/**
 * 把生成好的卡组数据打包成 gzip+base64 块，写进 src/data/deck-pack.ts。
 *
 * 为什么：卡片数据原本以明文对象字面量形式进 bundle（325 KB，且可直接 grep），
 * 打包后变成一块 base64（约 98 KB），bundle 更小、也不再是明文。
 * 注意这只是混淆与体积优化，不是加密——密钥必须随 app 下发，所以能解开的人都能解开。
 *
 * 用法：node scripts/pack-decks.mjs
 * 校验：npm run check:flashcards 会重算一遍并与已提交的 deck-pack.ts 比对，防止它过期。
 */
import { gzipSync } from 'node:zlib';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { readAllDecks } from './lib/deck-cards.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'src', 'data', 'deck-pack.ts');

/** 紧凑数组形式：[id, level, deck, category, front, back, source, verified] */
const packCard = (c) => [c.id, c.level || '', c.deck, c.category, c.front, c.back, c.source, c.verified ? 1 : 0];

export function buildPack(root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')) {
  const { amc10, subject } = readAllDecks(root);
  const payload = {
    amc10Decks: amc10.decks.map((d) => [d.key, d.label]),
    subjectDecks: subject.decks.map((d) => [d.key, d.label]),
    amc10Cards: amc10.cards.map(packCard),
    subjectCards: subject.cards.map(packCard),
  };
  const json = Buffer.from(JSON.stringify(payload), 'utf8');
  const gz = gzipSync(json, { level: 9 });
  return {
    payload,
    base64: gz.toString('base64'),
    rawBytes: json.length,
    gzBytes: gz.length,
    counts: { amc10: amc10.cards.length, subject: subject.cards.length },
  };
}

export function renderPackModule(pack) {
  return `// AUTO-GENERATED by scripts/pack-decks.mjs — do not hand-edit.
// Regenerate: node scripts/pack-decks.mjs
//
// 卡片数据以 base64(gzip(JSON)) 存放：${pack.counts.amc10} 张 AMC10 卡 + ${pack.counts.subject} 道选择题，
// 原始 ${(pack.rawBytes / 1024).toFixed(1)} KB → gzip ${(pack.gzBytes / 1024).toFixed(1)} KB → base64 ${(pack.base64.length / 1024).toFixed(1)} KB。
// 解开逻辑在 src/data/deck-pack-loader.ts；这只是混淆与体积优化，不是加密。

export const DECK_PACK_AMC10_CARDS = ${pack.counts.amc10};
export const DECK_PACK_SUBJECT_CARDS = ${pack.counts.subject};

export const DECK_PACK_BASE64 =
  '${pack.base64}';
`;
}

function main() {
  const pack = buildPack(root);
  writeFileSync(OUT, renderPackModule(pack));
  console.log(`wrote ${path.relative(root, OUT)}`);
  console.log(
    `cards amc10=${pack.counts.amc10} subject=${pack.counts.subject} | ` +
      `raw ${(pack.rawBytes / 1024).toFixed(1)}KB → gz ${(pack.gzBytes / 1024).toFixed(1)}KB → ` +
      `base64 ${(pack.base64.length / 1024).toFixed(1)}KB`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
